src/main: Add missing pthread header
Otherwise compilation can fail with:

main.cpp: In function 'void one_measurement(int, int, char*)':
main.cpp:226:3: error: 'pthread_t' was not declared in this scope
   pthread_t thread = 0UL;
   ^~~~~~~~~
main.cpp:226:3: note: suggested alternative: 'pread'
   pthread_t thread = 0UL;
   ^~~~~~~~~
   pread

et al.

Signed-off-by: Rosen Penev <rosenp@gmail.com>