[PATCH] resolve android build errors
- for android receiving compilation error
rapl_interface.cpp:195:40: error: call of overloaded 'pow(int, uint64_t)' is ambiguous

include/math.h:222:8: note: double pow(double, double).
stlport/stlport/stl/_cmath.h:453:24: note: float pow(float, float)

- these files are missing in the android makefile

Signed-off-by: Sanjay Singh Rawat <sanjay.rawat@linaro.org>