add missing stdio.h header
snprinf is defined in stdio.h.

Fixes:
perf/perf_bundle.cpp: In function ‘void parse_event_format(const char*)’:
perf/perf_bundle.cpp:141:75: error: ‘sprintf’ was not declared in this scope
  sprintf(file, "/sys/kernel/debug/tracing/events/%s/%s/format", sys, event);

Signed-off-by: Romain Naour <romain.naour@openwide.fr>