add missing sys/time.h header
struct timeval is defined in sys/time.h with a musl toolchain.

Fixes:
In file included from devices/devfreq.cpp:35:0:
devices/devfreq.h:35:18: error: field ‘stamp_before’ has incomplete type ‘timeval’
  struct timeval  stamp_before, stamp_after;

Signed-off-by: Romain Naour <romain.naour@openwide.fr>